const express = require('express')
const nodemailer = require('nodemailer');
const cors = require('cors')
require('dotenv').config();

const app = express()
const port = 3000
app.use(cors())

app.use(express.json());


let tranpoter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL, //your email
        pass: process.env.PASSWORD //your password generated by google
    }
})

app.get('/', (req, res) => {
  res.send('Ready to send the mail')
})

app.post('/send', (req, res) => {

    console.log(req.body);

    const data = JSON.stringify(req.body);

    let mailOptions = {
        from: 'atishay1950@gmail.com',
        to: 'info@redpositive.in',
        subject: 'Internshala intern application assignment text',
        text: data,
    }
    tranpoter.sendMail(mailOptions, function(err, data) {
    if(err) {
        console.log('Error Occur', err);
        res.send('Error occured')
    } else {
        console.log('mail sent')
        res.send('mail sent')
    }
    })
  
})

app.listen(port, () => {
  console.log(`server is running on port ${port}`)
})